class GameObjectConstants:
    # Клетки
    INITIAL_CELLS = 30
    CELL_SIZE = 25
    CELL_SPEED_MIN = 0.5
    CELL_SPEED_MAX = 2.0
    CELL_FIGHT_DISTANCE = 50
    
    # Патогены
    PATHOGEN_SIZE = 20
    PATHOGEN_STRENGTH_MIN = 5
    PATHOGEN_STRENGTH_MAX = 25
    PATHOGEN_SPEED_MIN = 0.3
    PATHOGEN_SPEED_MAX = 1.0
    PATHOGEN_STRENGTH_DECREASE = 0.5
    MAX_PATHOGENS = 10
    
    # Стимулы
    STIMULUS_DURATION_MIN = 200
    STIMULUS_DURATION_MAX = 500
    STIMULUS_INTENSITY_MIN = 0.5
    STIMULUS_INTENSITY_MAX = 2.0
    MAX_STIMULI = 5
    
    # Болезни
    DISEASE_SEVERITY_MIN = 0.1
    DISEASE_SEVERITY_MAX = 0.5
    DISEASE_DURATION_MIN = 1000
    DISEASE_DURATION_MAX = 3000
    
    # Генетика
    GENETIC_EFFECT_MIN = -0.2
    GENETIC_EFFECT_MAX = 0.2 