class GameBalanceConstants:
    # Факторы влияния
    HEALTH_FACTOR_BASE = 0.99995
    PATHOGEN_IMPACT_FACTOR = 0.00005
    STRESS_IMPACT_FACTOR = 0.00005
    DISEASE_IMPACT_FACTOR = 0.001
    
    # Пороговые значения
    NUTRIENT_BALANCE_THRESHOLD = 50
    NUTRIENT_BALANCE_FACTOR = 0.9
    ENERGY_BALANCE_THRESHOLD = 70
    
    # Изменения здоровья
    MAX_HEALTH_CHANGE = 0.01
    HEALTH_RECOVERY_FACTOR = 0.9999
    HEALTH_RECOVERY_AMOUNT = 0.005
    
    # Потребление и производство
    NUTRIENT_CONSUMPTION_GLUCOSE = 0.0001
    NUTRIENT_CONSUMPTION_OXYGEN = 0.00015
    HORMONE_PRODUCTION_AMOUNT = 0.0005
    ENERGY_INCREASE_AMOUNT = 0.0001
    ENERGY_DECREASE_AMOUNT = 0.0001
    
    # Вероятности появления
    PATHOGEN_APPEARANCE_PROBABILITY = 0.01
    STIMULUS_APPEARANCE_PROBABILITY = 0.01
    
    # Максимальные значения
    MAX_PATHOGENS = 5
    MAX_STIMULI = 3
    
    # Пороговые значения для окончания игры
    GAME_OVER_HEALTH_THRESHOLD = 0
    GAME_OVER_ENERGY_THRESHOLD = 0 